const TEAM_IDS = {
  GREAT_MAHI_MAHI: 1,
  MANITOBA_SHARPSHOOTERS: 2,
  RANSACKERS: 3,
  BUZZARDS: 4,
  RYNOS: 5,
  WEST_WILLOW_YACHT_CLUB: 6,
  TEAM_RAMROD: 7,
  BLOWFISH: 8,
  PECAN_MUDSLIDES: 9,
  ROADSIDE_ARMADILLOS: 10,
  HAVANA_RAFT_RUNNERS: 11,
  RIVER_CITY_WRANGLERS: 12,
  AVENGERS: 13,
  STEEL_CITY_ROUGHNECKS: 14
}